/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Confession {
  'id' : bigint,
  'status' : ContentStatus,
  'content' : string,
  'timestamp' : Time,
  'reports' : Array<Report>,
}
export type ContentStatus = { 'pending' : null } |
  { 'hidden' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ContentType = { 'resource' : null } |
  { 'event' : null } |
  { 'thread' : null } |
  { 'confession' : null };
export interface ModerationAction {
  'id' : bigint,
  'contentId' : bigint,
  'action' : ModerationActionType,
  'moderator' : Principal,
  'contentType' : ContentType,
  'note' : [] | [string],
  'timestamp' : Time,
}
export type ModerationActionType = { 'reject' : null } |
  { 'review' : null } |
  { 'hide' : null } |
  { 'approve' : null };
export interface NotificationPrefs {
  'sms' : boolean,
  'push' : boolean,
  'email' : boolean,
}
export interface Report { 'timestamp' : Time, 'reason' : string }
export interface Selector { 'pseudonym' : [] | [string] }
export interface SwipeStatus { 'matches' : Array<string> }
export type Time = bigint;
export interface UpdateLastSeenConfessionParams { 'lastSeenId' : bigint }
export interface UserProfile {
  'pseudonym' : [] | [string],
  'anonymousPosting' : boolean,
  'interests' : Array<string>,
  'pronouns' : [] | [string],
  'notificationPrefs' : NotificationPrefs,
  'hideProfile' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteConfession' : ActorMethod<[bigint], undefined>,
  'fetchSwipeCandidates' : ActorMethod<[], Array<Selector>>,
  'getAllContentIds' : ActorMethod<[ContentType], Array<bigint>>,
  'getApprovedConfessions' : ActorMethod<[bigint, bigint], Array<Confession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfession' : ActorMethod<[bigint], Confession>,
  'getConfessions' : ActorMethod<[Array<bigint>], Array<Confession>>,
  'getLatestModerationActionIds' : ActorMethod<[bigint], Array<bigint>>,
  'getModerationActions' : ActorMethod<
    [bigint, bigint],
    Array<ModerationAction>
  >,
  'getReportedConfessions' : ActorMethod<[], Array<Confession>>,
  'getReportedConfessionsByIds' : ActorMethod<
    [Array<bigint>],
    Array<Confession>
  >,
  'getUserMatches' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lastSeenConfession' : ActorMethod<[], [] | [bigint]>,
  'recordModerationAction' : ActorMethod<
    [bigint, ContentType, ModerationActionType, [] | [string]],
    undefined
  >,
  'recordSwipe' : ActorMethod<[string], SwipeStatus>,
  'reportConfession' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitConfession' : ActorMethod<[string], undefined>,
  'updateConfessionStatus' : ActorMethod<[bigint, ContentStatus], undefined>,
  'updateLastSeenConfession' : ActorMethod<
    [UpdateLastSeenConfessionParams],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];