/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Selector = IDL.Record({ 'pseudonym' : IDL.Opt(IDL.Text) });
export const ContentType = IDL.Variant({
  'resource' : IDL.Null,
  'event' : IDL.Null,
  'thread' : IDL.Null,
  'confession' : IDL.Null,
});
export const ContentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'hidden' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const Report = IDL.Record({ 'timestamp' : Time, 'reason' : IDL.Text });
export const Confession = IDL.Record({
  'id' : IDL.Nat,
  'status' : ContentStatus,
  'content' : IDL.Text,
  'timestamp' : Time,
  'reports' : IDL.Vec(Report),
});
export const NotificationPrefs = IDL.Record({
  'sms' : IDL.Bool,
  'push' : IDL.Bool,
  'email' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'pseudonym' : IDL.Opt(IDL.Text),
  'anonymousPosting' : IDL.Bool,
  'interests' : IDL.Vec(IDL.Text),
  'pronouns' : IDL.Opt(IDL.Text),
  'notificationPrefs' : NotificationPrefs,
  'hideProfile' : IDL.Bool,
});
export const ModerationActionType = IDL.Variant({
  'reject' : IDL.Null,
  'review' : IDL.Null,
  'hide' : IDL.Null,
  'approve' : IDL.Null,
});
export const ModerationAction = IDL.Record({
  'id' : IDL.Nat,
  'contentId' : IDL.Nat,
  'action' : ModerationActionType,
  'moderator' : IDL.Principal,
  'contentType' : ContentType,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const SwipeStatus = IDL.Record({ 'matches' : IDL.Vec(IDL.Text) });
export const UpdateLastSeenConfessionParams = IDL.Record({
  'lastSeenId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteConfession' : IDL.Func([IDL.Nat], [], []),
  'fetchSwipeCandidates' : IDL.Func([], [IDL.Vec(Selector)], ['query']),
  'getAllContentIds' : IDL.Func([ContentType], [IDL.Vec(IDL.Nat)], ['query']),
  'getApprovedConfessions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Confession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfession' : IDL.Func([IDL.Nat], [Confession], ['query']),
  'getConfessions' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Confession)],
      ['query'],
    ),
  'getLatestModerationActionIds' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getModerationActions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ModerationAction)],
      ['query'],
    ),
  'getReportedConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
  'getReportedConfessionsByIds' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Confession)],
      ['query'],
    ),
  'getUserMatches' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lastSeenConfession' : IDL.Func([], [IDL.Opt(IDL.Nat)], []),
  'recordModerationAction' : IDL.Func(
      [IDL.Nat, ContentType, ModerationActionType, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'recordSwipe' : IDL.Func([IDL.Text], [SwipeStatus], []),
  'reportConfession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitConfession' : IDL.Func([IDL.Text], [], []),
  'updateConfessionStatus' : IDL.Func([IDL.Nat, ContentStatus], [], []),
  'updateLastSeenConfession' : IDL.Func(
      [UpdateLastSeenConfessionParams],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Selector = IDL.Record({ 'pseudonym' : IDL.Opt(IDL.Text) });
  const ContentType = IDL.Variant({
    'resource' : IDL.Null,
    'event' : IDL.Null,
    'thread' : IDL.Null,
    'confession' : IDL.Null,
  });
  const ContentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'hidden' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const Report = IDL.Record({ 'timestamp' : Time, 'reason' : IDL.Text });
  const Confession = IDL.Record({
    'id' : IDL.Nat,
    'status' : ContentStatus,
    'content' : IDL.Text,
    'timestamp' : Time,
    'reports' : IDL.Vec(Report),
  });
  const NotificationPrefs = IDL.Record({
    'sms' : IDL.Bool,
    'push' : IDL.Bool,
    'email' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'pseudonym' : IDL.Opt(IDL.Text),
    'anonymousPosting' : IDL.Bool,
    'interests' : IDL.Vec(IDL.Text),
    'pronouns' : IDL.Opt(IDL.Text),
    'notificationPrefs' : NotificationPrefs,
    'hideProfile' : IDL.Bool,
  });
  const ModerationActionType = IDL.Variant({
    'reject' : IDL.Null,
    'review' : IDL.Null,
    'hide' : IDL.Null,
    'approve' : IDL.Null,
  });
  const ModerationAction = IDL.Record({
    'id' : IDL.Nat,
    'contentId' : IDL.Nat,
    'action' : ModerationActionType,
    'moderator' : IDL.Principal,
    'contentType' : ContentType,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const SwipeStatus = IDL.Record({ 'matches' : IDL.Vec(IDL.Text) });
  const UpdateLastSeenConfessionParams = IDL.Record({ 'lastSeenId' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteConfession' : IDL.Func([IDL.Nat], [], []),
    'fetchSwipeCandidates' : IDL.Func([], [IDL.Vec(Selector)], ['query']),
    'getAllContentIds' : IDL.Func([ContentType], [IDL.Vec(IDL.Nat)], ['query']),
    'getApprovedConfessions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Confession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfession' : IDL.Func([IDL.Nat], [Confession], ['query']),
    'getConfessions' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Confession)],
        ['query'],
      ),
    'getLatestModerationActionIds' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getModerationActions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ModerationAction)],
        ['query'],
      ),
    'getReportedConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
    'getReportedConfessionsByIds' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Confession)],
        ['query'],
      ),
    'getUserMatches' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lastSeenConfession' : IDL.Func([], [IDL.Opt(IDL.Nat)], []),
    'recordModerationAction' : IDL.Func(
        [IDL.Nat, ContentType, ModerationActionType, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'recordSwipe' : IDL.Func([IDL.Text], [SwipeStatus], []),
    'reportConfession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitConfession' : IDL.Func([IDL.Text], [], []),
    'updateConfessionStatus' : IDL.Func([IDL.Nat, ContentStatus], [], []),
    'updateLastSeenConfession' : IDL.Func(
        [UpdateLastSeenConfessionParams],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };