/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ModerationAction {
    id: bigint;
    contentId: bigint;
    action: ModerationActionType;
    moderator: Principal;
    contentType: ContentType;
    note?: string;
    timestamp: Time;
}
export type Time = bigint;
export interface Selector {
    pseudonym?: string;
}
export interface UpdateLastSeenConfessionParams {
    lastSeenId: bigint;
}
export interface Confession {
    id: bigint;
    status: ContentStatus;
    content: string;
    timestamp: Time;
    reports: Array<Report>;
}
export interface Report {
    timestamp: Time;
    reason: string;
}
export interface SwipeStatus {
    matches: Array<string>;
}
export interface UserProfile {
    pseudonym?: string;
    anonymousPosting: boolean;
    interests: Array<string>;
    pronouns?: string;
    notificationPrefs: NotificationPrefs;
    hideProfile: boolean;
}
export interface NotificationPrefs {
    sms: boolean;
    push: boolean;
    email: boolean;
}
export enum ContentStatus {
    pending = "pending",
    hidden = "hidden",
    approved = "approved",
    rejected = "rejected"
}
export enum ContentType {
    resource = "resource",
    event = "event",
    thread = "thread",
    confession = "confession"
}
export enum ModerationActionType {
    reject = "reject",
    review = "review",
    hide = "hide",
    approve = "approve"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteConfession(id: bigint): Promise<void>;
    fetchSwipeCandidates(): Promise<Array<Selector>>;
    getAllContentIds(contentType: ContentType): Promise<Array<bigint>>;
    getApprovedConfessions(offset: bigint, limit: bigint): Promise<Array<Confession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConfession(id: bigint): Promise<Confession>;
    getConfessions(ids: Array<bigint>): Promise<Array<Confession>>;
    getLatestModerationActionIds(count: bigint): Promise<Array<bigint>>;
    getModerationActions(limit: bigint, offset: bigint): Promise<Array<ModerationAction>>;
    getReportedConfessions(): Promise<Array<Confession>>;
    getReportedConfessionsByIds(ids: Array<bigint>): Promise<Array<Confession>>;
    getUserMatches(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    lastSeenConfession(): Promise<bigint | null>;
    recordModerationAction(contentId: bigint, contentType: ContentType, actionType: ModerationActionType, note: string | null): Promise<void>;
    recordSwipe(pseudonym: string): Promise<SwipeStatus>;
    reportConfession(confessionId: bigint, reason: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitConfession(content: string): Promise<void>;
    updateConfessionStatus(id: bigint, status: ContentStatus): Promise<void>;
    updateLastSeenConfession(params: UpdateLastSeenConfessionParams): Promise<void>;
}
import type { Confession as _Confession, ContentStatus as _ContentStatus, ContentType as _ContentType, ModerationAction as _ModerationAction, ModerationActionType as _ModerationActionType, NotificationPrefs as _NotificationPrefs, Report as _Report, Selector as _Selector, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteConfession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConfession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConfession(arg0);
            return result;
        }
    }
    async fetchSwipeCandidates(): Promise<Array<Selector>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSwipeCandidates();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSwipeCandidates();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContentIds(arg0: ContentType): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentIds(to_candid_ContentType_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentIds(to_candid_ContentType_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getApprovedConfessions(arg0: bigint, arg1: bigint): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedConfessions(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedConfessions(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfession(arg0: bigint): Promise<Confession> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfession(arg0);
                return from_candid_Confession_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfession(arg0);
            return from_candid_Confession_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfessions(arg0: Array<bigint>): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfessions(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfessions(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestModerationActionIds(arg0: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestModerationActionIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestModerationActionIds(arg0);
            return result;
        }
    }
    async getModerationActions(arg0: bigint, arg1: bigint): Promise<Array<ModerationAction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModerationActions(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModerationActions(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportedConfessions(): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportedConfessions();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportedConfessions();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportedConfessionsByIds(arg0: Array<bigint>): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportedConfessionsByIds(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportedConfessionsByIds(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMatches(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMatches();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async lastSeenConfession(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lastSeenConfession();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lastSeenConfession();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordModerationAction(arg0: bigint, arg1: ContentType, arg2: ModerationActionType, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordModerationAction(arg0, to_candid_ContentType_n7(this._uploadFile, this._downloadFile, arg1), to_candid_ModerationActionType_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordModerationAction(arg0, to_candid_ContentType_n7(this._uploadFile, this._downloadFile, arg1), to_candid_ModerationActionType_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async recordSwipe(arg0: string): Promise<SwipeStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSwipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSwipe(arg0);
            return result;
        }
    }
    async reportConfession(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportConfession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportConfession(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitConfession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitConfession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitConfession(arg0);
            return result;
        }
    }
    async updateConfessionStatus(arg0: bigint, arg1: ContentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConfessionStatus(arg0, to_candid_ContentStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConfessionStatus(arg0, to_candid_ContentStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLastSeenConfession(arg0: UpdateLastSeenConfessionParams): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastSeenConfession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastSeenConfession(arg0);
            return result;
        }
    }
}
function from_candid_Confession_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Confession): Confession {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ContentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentStatus): ContentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ModerationActionType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModerationActionType): ModerationActionType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ModerationAction_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModerationAction): ModerationAction {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Selector_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Selector): Selector {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ContentStatus;
    content: string;
    timestamp: _Time;
    reports: Array<_Report>;
}): {
    id: bigint;
    status: ContentStatus;
    content: string;
    timestamp: Time;
    reports: Array<Report>;
} {
    return {
        id: value.id,
        status: from_candid_ContentStatus_n12(_uploadFile, _downloadFile, value.status),
        content: value.content,
        timestamp: value.timestamp,
        reports: value.reports
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pseudonym: [] | [string];
    anonymousPosting: boolean;
    interests: Array<string>;
    pronouns: [] | [string];
    notificationPrefs: _NotificationPrefs;
    hideProfile: boolean;
}): {
    pseudonym?: string;
    anonymousPosting: boolean;
    interests: Array<string>;
    pronouns?: string;
    notificationPrefs: NotificationPrefs;
    hideProfile: boolean;
} {
    return {
        pseudonym: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.pseudonym)),
        anonymousPosting: value.anonymousPosting,
        interests: value.interests,
        pronouns: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.pronouns)),
        notificationPrefs: value.notificationPrefs,
        hideProfile: value.hideProfile
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contentId: bigint;
    action: _ModerationActionType;
    moderator: Principal;
    contentType: _ContentType;
    note: [] | [string];
    timestamp: _Time;
}): {
    id: bigint;
    contentId: bigint;
    action: ModerationActionType;
    moderator: Principal;
    contentType: ContentType;
    note?: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        contentId: value.contentId,
        action: from_candid_ModerationActionType_n22(_uploadFile, _downloadFile, value.action),
        moderator: value.moderator,
        contentType: from_candid_ContentType_n24(_uploadFile, _downloadFile, value.contentType),
        note: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.note)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pseudonym: [] | [string];
}): {
    pseudonym?: string;
} {
    return {
        pseudonym: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.pseudonym))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    hidden: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ContentStatus {
    return "pending" in value ? ContentStatus.pending : "hidden" in value ? ContentStatus.hidden : "approved" in value ? ContentStatus.approved : "rejected" in value ? ContentStatus.rejected : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reject: null;
} | {
    review: null;
} | {
    hide: null;
} | {
    approve: null;
}): ModerationActionType {
    return "reject" in value ? ModerationActionType.reject : "review" in value ? ModerationActionType.review : "hide" in value ? ModerationActionType.hide : "approve" in value ? ModerationActionType.approve : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resource: null;
} | {
    event: null;
} | {
    thread: null;
} | {
    confession: null;
}): ContentType {
    return "resource" in value ? ContentType.resource : "event" in value ? ContentType.event : "thread" in value ? ContentType.thread : "confession" in value ? ContentType.confession : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModerationAction>): Array<ModerationAction> {
    return value.map((x)=>from_candid_ModerationAction_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Selector>): Array<Selector> {
    return value.map((x)=>from_candid_Selector_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Confession>): Array<Confession> {
    return value.map((x)=>from_candid_Confession_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ContentStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): _ContentStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ContentType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ModerationActionType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModerationActionType): _ModerationActionType {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pseudonym?: string;
    anonymousPosting: boolean;
    interests: Array<string>;
    pronouns?: string;
    notificationPrefs: NotificationPrefs;
    hideProfile: boolean;
}): {
    pseudonym: [] | [string];
    anonymousPosting: boolean;
    interests: Array<string>;
    pronouns: [] | [string];
    notificationPrefs: _NotificationPrefs;
    hideProfile: boolean;
} {
    return {
        pseudonym: value.pseudonym ? candid_some(value.pseudonym) : candid_none(),
        anonymousPosting: value.anonymousPosting,
        interests: value.interests,
        pronouns: value.pronouns ? candid_some(value.pronouns) : candid_none(),
        notificationPrefs: value.notificationPrefs,
        hideProfile: value.hideProfile
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModerationActionType): {
    reject: null;
} | {
    review: null;
} | {
    hide: null;
} | {
    approve: null;
} {
    return value == ModerationActionType.reject ? {
        reject: null
    } : value == ModerationActionType.review ? {
        review: null
    } : value == ModerationActionType.hide ? {
        hide: null
    } : value == ModerationActionType.approve ? {
        approve: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): {
    pending: null;
} | {
    hidden: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ContentStatus.pending ? {
        pending: null
    } : value == ContentStatus.hidden ? {
        hidden: null
    } : value == ContentStatus.approved ? {
        approved: null
    } : value == ContentStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    resource: null;
} | {
    event: null;
} | {
    thread: null;
} | {
    confession: null;
} {
    return value == ContentType.resource ? {
        resource: null
    } : value == ContentType.event ? {
        event: null
    } : value == ContentType.thread ? {
        thread: null
    } : value == ContentType.confession ? {
        confession: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
